import {useState} from 'react'; import {Bell,Car,Eye,FileText,MessageSquare,MoreHorizontal,Plus,Search,ShieldCheck,Star,Upload,Users,type LucideIcon} from 'lucide-react'; import {Button} from '@/components/ui/button'; import {Badge} from '@/components/ui/badge'; import {Input} from '@/components/ui/input'; import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table'; import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog'; import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs'; import {Textarea} from '@/components/ui/textarea'; import {DashboardShell,AdminShell} from './dashboard-shell'; import {VehicleCard} from './cards'; import {VehicleFields,MockForm,Field} from './forms'; import {EmptyState,ErrorState,LoadingGrid} from './states'; import {vehicles,messages,notifications,reviews,parts,adminSections} from '@/data/mock-data'; import {VehicleImage} from './media'; import {Link} from '@tanstack/react-router'; import {ProfileForm,SettingsPanel} from './account-forms'; import {useAuth} from '@/lib/auth/auth-context'; import {profileCompleteness} from '@/lib/auth/profile-service';
const metrics: Array<[string,string,LucideIcon,string]>=[['Active listings','18',Car,'+3 this month'],['New enquiries','24',MessageSquare,'6 unread'],['Profile views','1,284',Eye,'+12.4%'],['Average rating','4.8',Star,'96 reviews']];
const adminMetrics: Array<[string,string,LucideIcon]>=[['Total users','12,840',Users],['Live vehicles','3,426',Car],['Pending checks','48',ShieldCheck],['Open reports','17',FileText]];
export function DashboardPage({page='overview'}:{page?:string}){return <DashboardShell><PageContent page={page}/></DashboardShell>}
function PageContent({page}:{page:string}){if(page==='overview')return <><Greeting/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon,note])=><div className="rounded-lg border bg-card p-5" key={label as string}><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label as string}</span><Icon className="size-5 text-primary"/></div><p className="mt-3 text-3xl font-bold">{value as string}</p><p className="mt-1 text-xs text-muted-foreground">{note as string}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Recent activity"><div className="space-y-4">{notifications.map(x=><div key={x.title} className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-primary"/><div><b className="text-sm">{x.title}</b><p className="text-sm text-muted-foreground">{x.body}</p></div><span className="ml-auto shrink-0 text-xs text-muted-foreground">{x.time}</span></div>)}</div></Panel><AccountReadiness/></div></>;
if(page==='saved')return <><Header title="Saved vehicles" body="Keep an eye on vehicles you’re considering."/><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{vehicles.slice(0,3).map(v=><VehicleCard key={v.id} v={v} saved/>)}</div></>;
if(page==='notifications')return <><Header title="Notifications" body="Updates about listings, enquiries and your account."/><Panel title="Recent notifications">{notifications.map(x=><div key={x.title} className="flex gap-3 border-b py-4 last:border-0"><Bell className="size-5 text-primary"/><div><b className="text-sm">{x.title}</b><p className="text-sm text-muted-foreground">{x.body}</p></div><span className="ml-auto text-xs text-muted-foreground">{x.time}</span></div>)}</Panel></>;
if(page==='messages'||page==='enquiries'||page==='requests')return <><Header title={page==='requests'?'Service requests':page==='enquiries'?'Enquiries':'Messages'} body="Review conversations and customer requests."/><Panel title="Inbox">{messages.map(x=><div key={x.name} className="grid grid-cols-[auto_minmax(0,1fr)_auto] gap-3 border-b py-4 last:border-0"><div className="grid size-10 place-items-center rounded-full bg-accent font-semibold text-primary">{x.name[0]}</div><div className="min-w-0"><b className="text-sm">{x.name}</b><p className="truncate text-sm text-muted-foreground">{x.subject} · {x.preview}</p></div><span className="text-xs text-muted-foreground">{x.time}</span></div>)}</Panel></>;
if(page==='reviews')return <><Header title="Reviews" body="Feedback shared through your Caryandi profile."/><div className="space-y-3">{reviews.map(r=><Panel key={r.name} title={r.name}><div className="flex gap-1">{Array.from({length:r.rating}).map((_,i)=><Star key={i} className="size-4 fill-warning text-warning"/>)}</div><p className="mt-3 text-sm text-muted-foreground">{r.text}</p></Panel>)}</div></>;
if(page==='add-vehicle'||page==='edit-vehicle')return <><Header title={page==='add-vehicle'?'Add a vehicle':'Edit vehicle'} body="Enter clear and accurate details for buyers."/><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><MockForm title="Vehicle details" submit={page==='add-vehicle'?'Preview listing':'Preview changes'}><VehicleFields/></MockForm><Panel title="Vehicle photos"><div className="grid aspect-square place-items-center rounded-lg border border-dashed bg-muted/30 text-center"><div><Upload className="mx-auto size-7 text-muted-foreground"/><b className="mt-2 block text-sm">Add clear photos</b><p className="text-xs text-muted-foreground">Front, rear, sides and interior</p></div></div><Button variant="outline" className="mt-3 w-full">Choose photos</Button></Panel></div></>;
if(['listings','inventory','parts','services','routes','availability','pricing','categories','team'].includes(page))return <ManagementTable page={page}/>;
if(page==='profile')return <><Header title="Profile" body="Manage your personal details and contact numbers."/><ProfileForm/></>;
if(page==='settings')return <><Header title="Settings" body="Manage your sign-in and account security."/><SettingsPanel/></>;
if(page==='verification')return <><Header title={page.charAt(0).toUpperCase()+page.slice(1)} body={`Manage your ${page} information.`}/><MockForm title={page==='verification'?'Verification details':'Account details'} submit="Preview changes"><div className="grid gap-5 sm:grid-cols-2"><Field label="Display name" placeholder="Mulenga Banda"/><Field label="Email address" type="email"/><Field label="Phone number"/><Field label="Location" placeholder="Lusaka"/></div><div className="grid gap-2"><label className="text-sm font-medium">About</label><Textarea rows={4}/></div></MockForm></>;
if(page==='add-part')return <><Header title="Add a part" body="Create a clear part listing for local buyers."/><MockForm title="Part details" submit="Preview part listing"><div className="grid gap-5 sm:grid-cols-2"><Field label="Part name"/><Field label="Category"/><Field label="Condition"/><Field label="Price (ZMW)"/><Field label="Compatible vehicles"/><Field label="Location"/></div></MockForm></>;
return <><Header title={page} body="This workspace is ready for production data."/><EmptyState/></>}
function ManagementTable({page}:{page:string}){const rows=page==='parts'?parts.map(x=>[x.name,x.category,`K${x.price.toLocaleString()}`,x.condition]):vehicles.map(x=>[x.name,x.location,`K${x.price.toLocaleString()}`,x.status??'Active']);return <><Header title={page.charAt(0).toUpperCase()+page.slice(1)} body="Review and manage your current items." action="Add new"/><div className="overflow-hidden rounded-lg border bg-card"><div className="flex gap-2 border-b p-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search items"/></div><Button variant="outline">Filter</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Location / category</TableHead><TableHead>Price</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r[0]}><TableCell className="font-medium">{r[0]}</TableCell><TableCell>{r[1]}</TableCell><TableCell>{r[2]}</TableCell><TableCell><Badge variant="outline">{r[3]}</Badge></TableCell><TableCell className="text-right"><Dialog><DialogTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Listing actions</DialogTitle><DialogDescription>Choose an action for {r[0]}.</DialogDescription></DialogHeader><div className="grid gap-2"><Button variant="outline">Edit details</Button><Button variant="outline">Change status</Button><Button variant="destructive">Remove listing</Button></div></DialogContent></Dialog></TableCell></TableRow>)}</TableBody></Table></div></div></>}
function Header({title,body,action}:{title:string;body:string;action?:string}){return <div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><h1 className="truncate text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{body}</p></div>{action&&<Button><Plus/>{action}</Button>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
export function AdminPage({page='overview'}:{page?:string}){if(page==='overview')return <AdminShell><Header title="Platform overview" body="Monitor marketplace activity and moderation queues."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{adminMetrics.map(([x,v,Icon])=><div className="rounded-lg border bg-card p-5" key={x}><Icon className="size-5 text-primary"/><p className="mt-4 text-sm text-muted-foreground">{x}</p><p className="text-3xl font-bold">{v}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><AdminTable title="Recent verification requests"/><Panel title="Platform areas">{adminSections.map(x=><div key={x} className="flex justify-between border-b py-2 text-sm last:border-0"><span>{x}</span><Badge variant="outline">Manage</Badge></div>)}</Panel></div></AdminShell>;return <AdminShell><Header title={page.charAt(0).toUpperCase()+page.slice(1)} body="Search, filter and review platform records."/><AdminTable title={`${page} management`}/><div className="mt-6"><Tabs defaultValue="data"><TabsList><TabsTrigger value="data">Data</TabsTrigger><TabsTrigger value="loading">Loading</TabsTrigger><TabsTrigger value="empty">Empty</TabsTrigger><TabsTrigger value="error">Error</TabsTrigger></TabsList></Tabs><div className="mt-4 grid gap-4 sm:grid-cols-3"><LoadingGrid/><EmptyState/><ErrorState/></div></div></AdminShell>}
function AdminTable({title}:{title:string}){return <div className="overflow-hidden rounded-lg border bg-card"><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_auto_auto]"><div><b>{title}</b><p className="text-xs text-muted-foreground">Visual management controls</p></div><Input placeholder="Search records"/><Button variant="outline">Filters</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead><TableHead>Updated</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{[['Autoworld Zambia','Dealer','Verified','Today'],['Mwamba J.','Private seller','Review','Today'],['Precision Auto Care','Mechanic','Verified','Yesterday'],['Zambezi Auto Imports','Agent','Pending','2 days ago']].map(r=><TableRow key={r[0]}><TableCell className="font-medium">{r[0]}</TableCell><TableCell>{r[1]}</TableCell><TableCell><Badge variant="outline">{r[2]}</Badge></TableCell><TableCell>{r[3]}</TableCell><TableCell><Dialog><DialogTrigger asChild><Button size="sm" variant="outline">Review</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Review {r[0]}</DialogTitle><DialogDescription>This moderation action is a visual demonstration only.</DialogDescription></DialogHeader><div className="rounded-md bg-muted p-4 text-sm">Submitted profile and verification details would appear here.</div><DialogFooter><Button variant="outline">Request changes</Button><Button>Preview approval</Button></DialogFooter></DialogContent></Dialog></TableCell></TableRow>)}</TableBody></Table></div></div>}

/** Time-of-day greeting with the signed-in user's first name. */
function Greeting(){const auth=useAuth(); const name=auth.status==='signed-in'?auth.account.profile.full_name.split(' ')[0]:''; const hour=new Date().getHours(); const part=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'; return <Header title={name?`${part}, ${name}`:part} body="Here’s what’s happening with your Caryandi account."/>}
/** Real profile completeness instead of a fixed percentage. */
function AccountReadiness(){const auth=useAuth(); if(auth.status!=='signed-in') return null; const {percent,missing}=profileCompleteness(auth.account); return <Panel title="Account readiness"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-success/10 text-success"><ShieldCheck/></div><div><b>Profile {percent}% complete</b><p className="text-sm text-muted-foreground">{missing.length?`Add ${missing.slice(0,2).join(' and ')} to build trust with buyers.`:'Your profile is complete.'}</p></div></div>{missing.length>0&&<Button variant="outline" className="mt-5 w-full" asChild><Link to="/dashboard/profile">Continue setup</Link></Button>}</Panel>}
