"""Builds supabase/content/information_guides.sql from supabase/content/guides/*.md.

Each guide file starts with 'key: value' lines (slug, category, title, summary), then '---',
then the article body in Caryandi's article format (see src/lib/content/article-format.ts).
Existing guides are never overwritten: once published, admins edit them in Admin > Content.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATEGORIES = {'registration', 'importing', 'duty_and_tax', 'documents', 'warning_lights', 'service_intervals', 'buying_safely', 'general'}
# Display order on /information (newest first, so publish times are staggered by a minute each).
ORDER = ['import-process', 'imports', 'duty-tax', 'documents', 'registration']

def load(path):
    head, body = path.read_text().split('\n---\n', 1)
    meta = dict(line.split(': ', 1) for line in head.strip().splitlines())
    assert re.fullmatch(r'[a-z0-9]+(-[a-z0-9]+)*', meta['slug']), path
    assert meta['category'] in CATEGORIES, path
    assert 3 <= len(meta['title']) <= 160 and len(meta['summary']) <= 300, path
    body = body.strip() + '\n'
    assert 50 <= len(body) <= 50000 and '$guide$' not in body, path
    return meta, body

def q(s): return "'" + s.replace("'", "''") + "'"

guides = {load(p)[0]['slug']: load(p) for p in sorted((ROOT / 'supabase/content/guides').glob('*.md'))}
assert set(guides) == set(ORDER), sorted(guides)
rows = []
SEP = ',\n'
for i, slug in enumerate(ORDER):
    meta, body = guides[slug]
    rows.append(f"  ({q(meta['slug'])}, {q(meta['category'])}, {q(meta['title'])}, {q(meta['summary'])},\n   $guide${body}$guide$, true, now() - interval '{i} minutes')")
sql = f"""-- Caryandi · information guides (generated by scripts/build_guides_sql.py — edit the .md files, not this)
-- Publishes the vehicle registration, import, duty and documents guides shown under /information.
-- Safe to run more than once: a guide that already exists (for example one an admin has edited)
-- is left untouched.
insert into public.info_articles (slug, category, title, summary, body, is_published, published_at)
values
{SEP.join(rows)}
on conflict (slug) do nothing;
"""
out = ROOT / 'supabase/content/information_guides.sql'
out.write_text(sql)
print(out.relative_to(ROOT), len(sql), 'chars')
