import {useState} from 'react'; import {Bell,Car,FileText,Heart,Loader2,MessageSquare,MoreHorizontal,Phone,Plus,Search,ShieldCheck,Star,Users,type LucideIcon} from 'lucide-react'; import {Button} from '@/components/ui/button'; import {Badge} from '@/components/ui/badge'; import {Input} from '@/components/ui/input'; import {Skeleton} from '@/components/ui/skeleton'; import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table'; import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog'; import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs'; import {Textarea} from '@/components/ui/textarea'; import {DashboardShell,AdminShell} from './dashboard-shell'; import {VehicleCard} from './cards'; import {EmptyState,ErrorState,LoadingGrid} from './states'; import {listMyTeam} from '@/lib/business/business-service'; import {Inbox,MeetupRequests} from './messaging-pages'; import {SellerVerification,AdminVerifications} from './verification-pages'; import {AdminBusinesses,AdminContent,AdminListings,AdminOverview,AdminReports,AdminReviews,AdminUsers} from './admin-pages'; import {Link} from '@tanstack/react-router'; import {ProfileForm,SettingsPanel} from './account-forms'; import {useAuth} from '@/lib/auth/auth-context'; import {profileCompleteness} from '@/lib/auth/profile-service';
import {useQuery,useQueryClient} from '@tanstack/react-query'; import {toast} from 'sonner'; import {isBusinessAccount} from '@/lib/auth/account-types'; import {queryKeys,useDashboardStats,useFavourites,useMyBusiness,useNotifications,useUserId} from '@/lib/marketplace/hooks'; import {listMyFavouriteVehicles,markNotificationsRead,timeAgo} from '@/lib/marketplace/engagement-service'; import {listReviewsAbout} from '@/lib/marketplace/seller-service'; import {safeRedirectPath} from '@/lib/auth/redirect'; import {BusinessProfileForm,MyListings,VehicleEditor} from './seller-pages'; import {AvailabilityEditor,MyParts,PartCategoriesOverview,PartEditor,PricingPanel,RoutesManager,ServicesManager} from './provider-dashboard';
export function DashboardPage({page='overview',vehicleId,partId,conversationId}:{page?:string;vehicleId?:string|undefined;partId?:string|undefined;conversationId?:string|undefined}){return <DashboardShell><PageContent page={page} vehicleId={vehicleId} partId={partId} conversationId={conversationId}/></DashboardShell>}
function PageContent({page,vehicleId,partId,conversationId}:{page:string;vehicleId?:string|undefined;partId?:string|undefined;conversationId?:string|undefined}){if(page==='overview')return <><Greeting/><DashboardMetrics/><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Recent activity"><RecentActivity/></Panel><AccountReadiness/></div></>;
if(page==='saved')return <><Header title="Saved vehicles" body="Keep an eye on vehicles you’re considering."/><SavedVehicles/></>;
if(page==='notifications')return <><Header title="Notifications" body="Updates about listings, enquiries and your account."/><NotificationsList/></>;
if(page==='messages')return <><Header title="Messages" body="Your conversations with sellers, dealers and service providers."/><Inbox conversationId={conversationId}/></>;
if(page==='enquiries')return <><Header title="Enquiries" body="Messages and viewing requests from buyers about your listings."/>{!conversationId&&<div className="mb-6"><h2 className="mb-3 font-semibold">Viewing and booking requests</h2><MeetupRequests/></div>}<Inbox received conversationId={conversationId}/></>;
if(page==='requests')return <><Header title="Service requests" body="Booking requests from customers. Accept, decline or mark them as done."/><MeetupRequests/><div className="mt-6"><h2 className="mb-3 font-semibold">Customer messages</h2><Inbox received basePath="/dashboard/requests" conversationId={conversationId}/></div></>;
if(page==='reviews')return <><Header title="Reviews" body="Feedback shared through your Caryandi profile."/><MyReviews/></>;
if(page==='add-vehicle')return <><Header title="Add a vehicle" body="Enter clear and accurate details for buyers."/><VehicleEditor/></>;
if(page==='edit-vehicle')return <><Header title="Edit vehicle" body="Update details, photos and documents, then publish when ready."/>{vehicleId?<VehicleEditor key={vehicleId} vehicleId={vehicleId}/>:<EmptyState title="Choose a vehicle to edit" body="Open one of your listings to edit it."/>}</>;
if(page==='listings'||page==='inventory')return <><Header title={page==='inventory'?'Inventory':'Listings'} body="Manage your vehicles, publish drafts and mark cars as sold." action="Add vehicle" actionTo="/dashboard/add-vehicle"/><MyListings/></>;
if(page==='parts')return <><Header title="Parts inventory" body="Manage your parts, publish drafts and mark items as sold." action="Add part" actionTo="/dashboard/add-part"/><MyParts/></>;
if(page==='categories')return <><Header title="Categories" body="How your parts are spread across Caryandi’s categories."/><PartCategoriesOverview/></>;
if(page==='services')return <><Header title="Services" body="What you offer, with starting prices customers can compare."/><ServicesManager/></>;
if(page==='routes')return <><Header title="Import routes" body="The routes you handle, with services, prices and delivery times."/><RoutesManager/></>;
if(page==='availability')return <><Header title="Availability" body="Opening hours and whether you come to customers."/><AvailabilityEditor/></>;
if(page==='pricing')return <><Header title="Pricing" body="Your starting price and an overview of what you charge."/><PricingPanel/></>;
if(page==='team')return <><Header title="Team summary" body="People who can manage your dealership on Caryandi."/><TeamSummary/></>;
if(page==='profile')return <><Header title="Profile" body="Manage your personal details and contact numbers."/><BusinessProfileSection/><ProfileForm/></>;
if(page==='settings')return <><Header title="Settings" body="Manage your sign-in and account security."/><SettingsPanel/></>;
if(page==='verification')return <><Header title="Verification" body="Earn the verified badge buyers look for. It’s optional and free."/><SellerVerification/></>;
if(page==='add-part')return <><Header title={partId?'Edit part':'Add a part'} body={partId?'Update details and photos, then publish when ready.':'Create a clear part listing for local buyers.'}/><PartEditor key={partId??'new'} partId={partId}/></>;
return <><Header title={page} body="This workspace is ready for production data."/><EmptyState/></>}
function TeamSummary(){const business=useMyBusiness(); const businessId=business.data?.business.id; const team=useQuery({queryKey:['team',businessId??'none'],queryFn:()=>listMyTeam(businessId!),enabled:Boolean(businessId)});
  if(business.isPending||(businessId&&team.isPending)) return <LoadingGrid/>; if(business.isError||team.isError) return <ErrorState message="We couldn’t load your team." onRetry={()=>{void business.refetch(); void team.refetch();}}/>;
  if(!business.data) return <EmptyState title="No business profile yet" body="Set up your dealership profile first; you’ll appear here as its owner."/>;
  const members=team.data??[]; const ROLE:Record<string,string>={owner:'Owner',manager:'Manager',staff:'Staff'};
  return <Panel title={`${members.length} ${members.length===1?'person':'people'}`}>{members.map(m=><div key={m.profileId} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b py-3 last:border-0"><div className="grid size-10 place-items-center rounded-full bg-accent font-semibold text-primary">{m.name.charAt(0)}</div><div className="min-w-0"><b className="block truncate text-sm">{m.name}</b><span className="text-xs text-muted-foreground">Joined {timeAgo(m.joinedAt)}</span></div><Badge variant={m.role==='owner'?'default':'outline'}>{ROLE[m.role]??m.role}</Badge></div>)}<p className="mt-3 text-xs text-muted-foreground">Inviting staff accounts is not available yet. Team members can already reply to enquiries and meet-up requests for your listings.</p></Panel>}
function Header({title,body,action,actionTo}:{title:string;body:string;action?:string;actionTo?:string}){return <div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><h1 className="truncate text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{body}</p></div>{action&&(actionTo?<Button asChild><Link to={actionTo as never}><Plus/>{action}</Link></Button>:<Button><Plus/>{action}</Button>)}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
const ADMIN_PAGES:Record<string,[string,string]>={users:['Users','Search accounts and suspend, ban or reactivate them. Every action is recorded.'],sellers:['Private sellers','People selling their own vehicles.'],dealers:['Dealers','Dealerships and their stock.'],mechanics:['Mechanics','Independent mechanics and garages.'],'servicing-companies':['Servicing companies','Service centres and workshops.'],'parts-sellers':['Parts sellers','Businesses selling parts.'],'import-agents':['Import agents','Agents and their import routes.'],vehicles:['Vehicles & parts','Moderate listings. Taking one down notifies the seller with your reason.'],reports:['Reports','Scam reports come first. Contact details are only released for scam reports under review.'],reviews:['Reviews','Hide reviews that break the rules; ratings are recalculated automatically.'],content:['Information content','Guides shown on the Information pages.']};
const BUSINESS_PAGES:Record<string,'dealer'|'mechanic'|'servicing_company'|'parts_seller'|'import_agent'>={dealers:'dealer',mechanics:'mechanic','servicing-companies':'servicing_company','parts-sellers':'parts_seller','import-agents':'import_agent'};
export function AdminPage({page='overview'}:{page?:string}){
  if(page==='overview')return <AdminShell><Header title="Platform overview" body="Monitor marketplace activity and moderation queues."/><AdminOverview/></AdminShell>;
  if(page==='verifications')return <AdminShell><Header title="Verification requests" body="Check each in-app selfie and document, then approve or explain what’s missing."/><AdminVerifications/></AdminShell>;
  const [title,body]=ADMIN_PAGES[page]??[page,'']; const businessType=BUSINESS_PAGES[page];
  return <AdminShell><Header title={title} body={body}/>{businessType?<AdminBusinesses key={businessType} type={businessType}/>:page==='users'?<AdminUsers key="all"/>:page==='sellers'?<AdminUsers key="private" fixedType="private_seller"/>:page==='vehicles'?<AdminListings/>:page==='reviews'?<AdminReviews/>:page==='reports'?<AdminReports/>:page==='content'?<AdminContent/>:<EmptyState title="Page not found" body="Choose an area from the menu."/>}</AdminShell>}

/** Time-of-day greeting with the signed-in user's first name. */
function Greeting(){const auth=useAuth(); const name=auth.status==='signed-in'?auth.account.profile.full_name.split(' ')[0]:''; const hour=new Date().getHours(); const part=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'; return <Header title={name?`${part}, ${name}`:part} body="Here’s what’s happening with your Caryandi account."/>}
/** Real profile completeness instead of a fixed percentage. */
function AccountReadiness(){const auth=useAuth(); if(auth.status!=='signed-in') return null; const {percent,missing}=profileCompleteness(auth.account); return <Panel title="Account readiness"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-success/10 text-success"><ShieldCheck/></div><div><b>Profile {percent}% complete</b><p className="text-sm text-muted-foreground">{missing.length?`Add ${missing.slice(0,2).join(' and ')} to build trust with buyers.`:'Your profile is complete.'}</p></div></div>{missing.length>0&&<Button variant="outline" className="mt-5 w-full" asChild><Link to="/dashboard/profile">Continue setup</Link></Button>}</Panel>}

/* ---------------------------------------------------------------- Stage 3: real data */

const VEHICLE_SELLER_TYPES=['private_seller','dealer','import_agent'];
function Metric({label,value,Icon,note,loading}:{label:string;value:string;Icon:LucideIcon;note:string;loading?:boolean}){return <div className="rounded-lg border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className="size-5 text-primary"/></div>{loading?<Skeleton className="mt-3 h-9 w-16"/>:<p className="mt-3 text-3xl font-bold">{value}</p>}<p className="mt-1 text-xs text-muted-foreground">{note}</p></div>}
/** Live numbers from the database (my_dashboard_stats) instead of fixed demo figures. */
function DashboardMetrics(){const auth=useAuth(); const stats=useDashboardStats(); const favourites=useFavourites(); const business=useMyBusiness(); if(auth.status!=='signed-in') return null;
  const p=auth.account.profile; const s=stats.data; const loading=stats.isPending; const n=(x:number|undefined)=>(x??0).toLocaleString();
  const rated=business.data?.business??p; const ratingCount=rated.rating_count??0; const rating=ratingCount>0?Number(rated.rating_avg??0).toFixed(1):'—'; const ratingNote=ratingCount>0?`${ratingCount} review${ratingCount===1?'':'s'}`:'No reviews yet';
  if(stats.isError) return <ErrorState message="We couldn’t load your dashboard numbers." onRetry={()=>void stats.refetch()}/>;
  const tiles:Array<[string,string,LucideIcon,string]>=VEHICLE_SELLER_TYPES.includes(p.account_type)
    ?[['Live listings',n(s?.active_listings),Car,`${n(s?.draft_listings)} drafts · ${n(s?.sold_listings)} sold`],['Contact requests',n(s?.contact_requests_7d),Phone,`Last 7 days · ${n(s?.contact_requests_total)} all time`],['Times saved',n(s?.times_saved),Heart,'Buyers who saved your vehicles'],['Average rating',rating,Star,ratingNote]]
    :[['Saved vehicles',favourites.count.toLocaleString(),Heart,'Vehicles you’re keeping an eye on'],['Unread notifications',n(s?.unread_notifications),Bell,'Updates about your account'],...(business.data?[['Average rating',rating,Star,ratingNote] as [string,string,LucideIcon,string]]:[])];
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{tiles.map(([label,value,Icon,note])=><Metric key={label} label={label} value={value} Icon={Icon} note={note} loading={loading}/>)}</div>}
function RecentActivity(){const q=useNotifications(5); if(q.isPending) return <div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-10 w-full"/>)}</div>; if(q.isError) return <p className="text-sm text-muted-foreground">We couldn’t load your recent activity.</p>; if(!q.data.length) return <p className="text-sm text-muted-foreground">No activity yet. Updates about your listings and account will appear here.</p>;
  return <div className="space-y-4">{q.data.map(x=><div key={x.id} className="flex gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${x.read_at?'bg-muted-foreground/30':'bg-primary'}`}/><div className="min-w-0"><b className="text-sm">{x.title}</b>{x.body&&<p className="text-sm text-muted-foreground">{x.body}</p>}</div><span className="ml-auto shrink-0 text-xs text-muted-foreground">{timeAgo(x.created_at)}</span></div>)}<Link to="/dashboard/notifications" className="block text-sm font-semibold text-primary">View all notifications</Link></div>}
function SavedVehicles(){const uid=useUserId(); const {isSaved,toggle,ready}=useFavourites(); const q=useQuery({queryKey:queryKeys.favouriteVehicles(uid??'anon'),queryFn:listMyFavouriteVehicles,enabled:Boolean(uid)});
  if(q.isPending) return <LoadingGrid/>; if(q.isError) return <ErrorState message="We couldn’t load your saved vehicles." onRetry={()=>void q.refetch()}/>;
  // Hide cards the moment they're un-saved, before the refetch finishes.
  const items=ready?q.data.filter(v=>isSaved(v.id)):q.data; if(!items.length) return <><EmptyState title="No saved vehicles yet" body="Tap the heart on any vehicle to keep it here."/><div className="mt-4 text-center"><Button asChild><Link to="/vehicles">Browse vehicles</Link></Button></div></>;
  return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(v=><VehicleCard key={v.id} v={v} saved onSave={()=>v.id&&toggle(v.id)}/>)}</div>}
function NotificationsList(){const uid=useUserId(); const queryClient=useQueryClient(); const q=useNotifications(100); const [busy,setBusy]=useState(false);
  const unread=(q.data??[]).filter(x=>!x.read_at).map(x=>x.id);
  const markAll=async()=>{setBusy(true); try{await markNotificationsRead(unread); if(uid){await queryClient.invalidateQueries({queryKey:queryKeys.notifications(uid)}); void queryClient.invalidateQueries({queryKey:queryKeys.stats(uid)});}}catch(e){toast.error(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}};
  if(q.isPending) return <Panel title="Recent notifications"><div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-12 w-full"/>)}</div></Panel>; if(q.isError) return <ErrorState message="We couldn’t load your notifications." onRetry={()=>void q.refetch()}/>; if(!q.data.length) return <EmptyState title="No notifications yet" body="We’ll let you know about your listings, reviews and account here."/>;
  return <Panel title={unread.length?`${unread.length} unread`:'Recent notifications'}>{unread.length>0&&<Button variant="outline" size="sm" className="mb-2" disabled={busy} onClick={()=>void markAll()}>{busy&&<Loader2 className="animate-spin"/>}Mark all as read</Button>}{q.data.map(x=>{const inner=<><Bell className={`size-5 shrink-0 ${x.read_at?'text-muted-foreground':'text-primary'}`}/><div className="min-w-0"><b className="text-sm">{x.title}</b>{x.body&&<p className="text-sm text-muted-foreground">{x.body}</p>}</div><span className="ml-auto shrink-0 text-xs text-muted-foreground">{timeAgo(x.created_at)}</span></>; const internal=safeRedirectPath(x.link); const [linkPath,linkQuery]=(internal??'').split('?'); const linkSearch=Object.fromEntries(new URLSearchParams(linkQuery??'')); return internal?<Link key={x.id} to={linkPath as never} search={linkSearch as never} onClick={()=>{if(!x.read_at) void markNotificationsRead([x.id]).then(()=>uid&&queryClient.invalidateQueries({queryKey:queryKeys.notifications(uid)}))}} className={`flex gap-3 border-b py-4 last:border-0 hover:bg-accent/40 ${x.read_at?'':'font-medium'}`}>{inner}</Link>:<div key={x.id} className="flex gap-3 border-b py-4 last:border-0">{inner}</div>})}</Panel>}
function MyReviews(){const uid=useUserId(); const business=useMyBusiness(); const businessId=business.data?.business.id??null; const q=useQuery({queryKey:[...queryKeys.reviewsAbout(uid??'anon'),businessId],queryFn:()=>listReviewsAbout({businessId,sellerId:uid}),enabled:Boolean(uid)&&!business.isPending});
  if(q.isPending) return <LoadingGrid/>; if(q.isError) return <ErrorState message="We couldn’t load your reviews." onRetry={()=>void q.refetch()}/>; if(!q.data.length) return <EmptyState title="No reviews yet" body="Reviews from buyers you’ve dealt with will appear here."/>;
  return <div className="space-y-3">{q.data.map(r=><Panel key={r.id} title={r.reviewer_name??'Caryandi user'}><div className="flex gap-1" aria-label={`${r.rating} out of 5`}>{Array.from({length:r.rating??0}).map((_,i)=><Star key={i} className="size-4 fill-warning text-warning"/>)}</div>{r.body&&<p className="mt-3 text-sm text-muted-foreground">{r.body}</p>}{r.created_at&&<p className="mt-2 text-xs text-muted-foreground">{timeAgo(r.created_at)}</p>}</Panel>)}</div>}
/** Business accounts manage their public business profile above their personal details. */
function BusinessProfileSection(){const auth=useAuth(); if(auth.status!=='signed-in'||!isBusinessAccount(auth.account.profile.account_type)) return null; return <div className="mb-8"><BusinessProfileForm/><h2 className="mt-10 text-lg font-semibold">Your personal details</h2><p className="mb-4 text-sm text-muted-foreground">Your own account, separate from the business.</p></div>}
