import {useState} from 'react'; import {Bell,Car,FileText,Heart,Loader2,MessageSquare,MoreHorizontal,Phone,Plus,Search,ShieldCheck,Star,Users,type LucideIcon} from 'lucide-react'; import {Button} from '@/components/ui/button'; import {Badge} from '@/components/ui/badge'; import {Input} from '@/components/ui/input'; import {Skeleton} from '@/components/ui/skeleton'; import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table'; import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog'; import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs'; import {Textarea} from '@/components/ui/textarea'; import {DashboardShell,AdminShell} from './dashboard-shell'; import {VehicleCard} from './cards'; import {EmptyState,ErrorState,LoadingGrid} from './states'; import {vehicles,messages,adminSections} from '@/data/mock-data'; import {SelfieReviewNote} from './selfie-capture'; import {SellerVerification,AdminVerifications} from './verification-pages'; import {Link} from '@tanstack/react-router'; import {ProfileForm,SettingsPanel} from './account-forms'; import {useAuth} from '@/lib/auth/auth-context'; import {profileCompleteness} from '@/lib/auth/profile-service';
import {useQuery,useQueryClient} from '@tanstack/react-query'; import {toast} from 'sonner'; import {isBusinessAccount} from '@/lib/auth/account-types'; import {queryKeys,useDashboardStats,useFavourites,useMyBusiness,useNotifications,useUserId} from '@/lib/marketplace/hooks'; import {listMyFavouriteVehicles,markNotificationsRead,timeAgo} from '@/lib/marketplace/engagement-service'; import {listReviewsAbout} from '@/lib/marketplace/seller-service'; import {safeRedirectPath} from '@/lib/auth/redirect'; import {BusinessProfileForm,MyListings,VehicleEditor} from './seller-pages'; import {AvailabilityEditor,MyParts,PartCategoriesOverview,PartEditor,PricingPanel,RoutesManager,ServicesManager} from './provider-dashboard';
const adminMetrics: Array<[string,string,LucideIcon]>=[['Total users','12,840',Users],['Live vehicles','3,426',Car],['Pending checks','48',ShieldCheck],['Open reports','17',FileText]];
export function DashboardPage({page='overview',vehicleId,partId}:{page?:string;vehicleId?:string|undefined;partId?:string|undefined}){return <DashboardShell><PageContent page={page} vehicleId={vehicleId} partId={partId}/></DashboardShell>}
function PageContent({page,vehicleId,partId}:{page:string;vehicleId?:string|undefined;partId?:string|undefined}){if(page==='overview')return <><Greeting/><DashboardMetrics/><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Recent activity"><RecentActivity/></Panel><AccountReadiness/></div></>;
if(page==='saved')return <><Header title="Saved vehicles" body="Keep an eye on vehicles you’re considering."/><SavedVehicles/></>;
if(page==='notifications')return <><Header title="Notifications" body="Updates about listings, enquiries and your account."/><NotificationsList/></>;
if(page==='messages'||page==='enquiries'||page==='requests')return <><Header title={page==='requests'?'Service requests':page==='enquiries'?'Enquiries':'Messages'} body="Review conversations and customer requests."/><Panel title="Inbox">{messages.map(x=><div key={x.name} className="grid grid-cols-[auto_minmax(0,1fr)_auto] gap-3 border-b py-4 last:border-0"><div className="grid size-10 place-items-center rounded-full bg-accent font-semibold text-primary">{x.name[0]}</div><div className="min-w-0"><b className="text-sm">{x.name}</b><p className="truncate text-sm text-muted-foreground">{x.subject} · {x.preview}</p></div><span className="text-xs text-muted-foreground">{x.time}</span></div>)}</Panel></>;
if(page==='reviews')return <><Header title="Reviews" body="Feedback shared through your Caryandi profile."/><MyReviews/></>;
if(page==='add-vehicle')return <><Header title="Add a vehicle" body="Enter clear and accurate details for buyers."/><VehicleEditor/></>;
if(page==='edit-vehicle')return <><Header title="Edit vehicle" body="Update details, photos and documents, then publish when ready."/>{vehicleId?<VehicleEditor key={vehicleId} vehicleId={vehicleId}/>:<EmptyState title="Choose a vehicle to edit" body="Open one of your listings to edit it."/>}</>;
if(page==='listings'||page==='inventory')return <><Header title={page==='inventory'?'Inventory':'Listings'} body="Manage your vehicles, publish drafts and mark cars as sold." action="Add vehicle" actionTo="/dashboard/add-vehicle"/><MyListings/></>;
if(page==='parts')return <><Header title="Parts inventory" body="Manage your parts, publish drafts and mark items as sold." action="Add part" actionTo="/dashboard/add-part"/><MyParts/></>;
if(page==='categories')return <><Header title="Categories" body="How your parts are spread across Caryandi’s categories."/><PartCategoriesOverview/></>;
if(page==='services')return <><Header title="Services" body="What you offer, with starting prices customers can compare."/><ServicesManager/></>;
if(page==='routes')return <><Header title="Import routes" body="The routes you handle, with services, prices and delivery times."/><RoutesManager/></>;
if(page==='availability')return <><Header title="Availability" body="Opening hours and whether you come to customers."/><AvailabilityEditor/></>;
if(page==='pricing')return <><Header title="Pricing" body="Your starting price and an overview of what you charge."/><PricingPanel/></>;
if(['listings','inventory','team'].includes(page))return <ManagementTable page={page}/>;
if(page==='profile')return <><Header title="Profile" body="Manage your personal details and contact numbers."/><BusinessProfileSection/><ProfileForm/></>;
if(page==='settings')return <><Header title="Settings" body="Manage your sign-in and account security."/><SettingsPanel/></>;
if(page==='verification')return <><Header title="Verification" body="Earn the verified badge buyers look for. It’s optional and free."/><SellerVerification/></>;
if(page==='add-part')return <><Header title={partId?'Edit part':'Add a part'} body={partId?'Update details and photos, then publish when ready.':'Create a clear part listing for local buyers.'}/><PartEditor key={partId??'new'} partId={partId}/></>;
return <><Header title={page} body="This workspace is ready for production data."/><EmptyState/></>}
function ManagementTable({page}:{page:string}){const rows=vehicles.map(x=>[x.name,x.location,`K${x.price.toLocaleString()}`,x.status??'Active']);return <><Header title={page.charAt(0).toUpperCase()+page.slice(1)} body="Review and manage your current items." action="Add new"/><div className="overflow-hidden rounded-lg border bg-card"><div className="flex gap-2 border-b p-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search items"/></div><Button variant="outline">Filter</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Location / category</TableHead><TableHead>Price</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r[0]}><TableCell className="font-medium">{r[0]}</TableCell><TableCell>{r[1]}</TableCell><TableCell>{r[2]}</TableCell><TableCell><Badge variant="outline">{r[3]}</Badge></TableCell><TableCell className="text-right"><Dialog><DialogTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Listing actions</DialogTitle><DialogDescription>Choose an action for {r[0]}.</DialogDescription></DialogHeader><div className="grid gap-2"><Button variant="outline">Edit details</Button><Button variant="outline">Change status</Button><Button variant="destructive">Remove listing</Button></div></DialogContent></Dialog></TableCell></TableRow>)}</TableBody></Table></div></div></>}
function Header({title,body,action,actionTo}:{title:string;body:string;action?:string;actionTo?:string}){return <div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><h1 className="truncate text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{body}</p></div>{action&&(actionTo?<Button asChild><Link to={actionTo as never}><Plus/>{action}</Link></Button>:<Button><Plus/>{action}</Button>)}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
export function AdminPage({page='overview'}:{page?:string}){if(page==='overview')return <AdminShell><Header title="Platform overview" body="Monitor marketplace activity and moderation queues."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{adminMetrics.map(([x,v,Icon])=><div className="rounded-lg border bg-card p-5" key={x}><Icon className="size-5 text-primary"/><p className="mt-4 text-sm text-muted-foreground">{x}</p><p className="text-3xl font-bold">{v}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><AdminTable title="Recent verification requests"/><Panel title="Platform areas">{adminSections.map(x=><div key={x} className="flex justify-between border-b py-2 text-sm last:border-0"><span>{x}</span><Badge variant="outline">Manage</Badge></div>)}</Panel></div></AdminShell>;if(page==='verifications')return <AdminShell><Header title="Verification requests" body="Check each in-app selfie and document, then approve or explain what’s missing."/><AdminVerifications/></AdminShell>;return <AdminShell><Header title={page.charAt(0).toUpperCase()+page.slice(1)} body="Search, filter and review platform records."/><AdminTable title={`${page} management`}/><div className="mt-6"><Tabs defaultValue="data"><TabsList><TabsTrigger value="data">Data</TabsTrigger><TabsTrigger value="loading">Loading</TabsTrigger><TabsTrigger value="empty">Empty</TabsTrigger><TabsTrigger value="error">Error</TabsTrigger></TabsList></Tabs><div className="mt-4 grid gap-4 sm:grid-cols-3"><LoadingGrid/><EmptyState/><ErrorState/></div></div></AdminShell>}
function AdminTable({title}:{title:string}){return <div className="overflow-hidden rounded-lg border bg-card"><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_auto_auto]"><div><b>{title}</b><p className="text-xs text-muted-foreground">Visual management controls</p></div><Input placeholder="Search records"/><Button variant="outline">Filters</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead><TableHead>Updated</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{[['Autoworld Zambia','Dealer','Verified','Today'],['Mwamba J.','Private seller','Review','Today'],['Precision Auto Care','Mechanic','Verified','Yesterday'],['Zambezi Auto Imports','Agent','Pending','2 days ago']].map(r=><TableRow key={r[0]}><TableCell className="font-medium">{r[0]}</TableCell><TableCell>{r[1]}</TableCell><TableCell><Badge variant="outline">{r[2]}</Badge></TableCell><TableCell>{r[3]}</TableCell><TableCell><Dialog><DialogTrigger asChild><Button size="sm" variant="outline">Review</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Review {r[0]}</DialogTitle><DialogDescription>This moderation action is a visual demonstration only.</DialogDescription></DialogHeader><div className="grid gap-3"><div className="rounded-md bg-muted p-4 text-sm">Submitted profile, live selfie and verification documents would appear here.</div><SelfieReviewNote/></div><DialogFooter><Button variant="outline">Request changes</Button><Button>Preview approval</Button></DialogFooter></DialogContent></Dialog></TableCell></TableRow>)}</TableBody></Table></div></div>}

/** Time-of-day greeting with the signed-in user's first name. */
function Greeting(){const auth=useAuth(); const name=auth.status==='signed-in'?auth.account.profile.full_name.split(' ')[0]:''; const hour=new Date().getHours(); const part=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'; return <Header title={name?`${part}, ${name}`:part} body="Here’s what’s happening with your Caryandi account."/>}
/** Real profile completeness instead of a fixed percentage. */
function AccountReadiness(){const auth=useAuth(); if(auth.status!=='signed-in') return null; const {percent,missing}=profileCompleteness(auth.account); return <Panel title="Account readiness"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-success/10 text-success"><ShieldCheck/></div><div><b>Profile {percent}% complete</b><p className="text-sm text-muted-foreground">{missing.length?`Add ${missing.slice(0,2).join(' and ')} to build trust with buyers.`:'Your profile is complete.'}</p></div></div>{missing.length>0&&<Button variant="outline" className="mt-5 w-full" asChild><Link to="/dashboard/profile">Continue setup</Link></Button>}</Panel>}

/* ---------------------------------------------------------------- Stage 3: real data */

const VEHICLE_SELLER_TYPES=['private_seller','dealer','import_agent'];
function Metric({label,value,Icon,note,loading}:{label:string;value:string;Icon:LucideIcon;note:string;loading?:boolean}){return <div className="rounded-lg border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className="size-5 text-primary"/></div>{loading?<Skeleton className="mt-3 h-9 w-16"/>:<p className="mt-3 text-3xl font-bold">{value}</p>}<p className="mt-1 text-xs text-muted-foreground">{note}</p></div>}
/** Live numbers from the database (my_dashboard_stats) instead of fixed demo figures. */
function DashboardMetrics(){const auth=useAuth(); const stats=useDashboardStats(); const favourites=useFavourites(); const business=useMyBusiness(); if(auth.status!=='signed-in') return null;
  const p=auth.account.profile; const s=stats.data; const loading=stats.isPending; const n=(x:number|undefined)=>(x??0).toLocaleString();
  const rated=business.data?.business??p; const ratingCount=rated.rating_count??0; const rating=ratingCount>0?Number(rated.rating_avg??0).toFixed(1):'—'; const ratingNote=ratingCount>0?`${ratingCount} review${ratingCount===1?'':'s'}`:'No reviews yet';
  if(stats.isError) return <ErrorState message="We couldn’t load your dashboard numbers." onRetry={()=>void stats.refetch()}/>;
  const tiles:Array<[string,string,LucideIcon,string]>=VEHICLE_SELLER_TYPES.includes(p.account_type)
    ?[['Live listings',n(s?.active_listings),Car,`${n(s?.draft_listings)} drafts · ${n(s?.sold_listings)} sold`],['Contact requests',n(s?.contact_requests_7d),Phone,`Last 7 days · ${n(s?.contact_requests_total)} all time`],['Times saved',n(s?.times_saved),Heart,'Buyers who saved your vehicles'],['Average rating',rating,Star,ratingNote]]
    :[['Saved vehicles',favourites.count.toLocaleString(),Heart,'Vehicles you’re keeping an eye on'],['Unread notifications',n(s?.unread_notifications),Bell,'Updates about your account'],...(business.data?[['Average rating',rating,Star,ratingNote] as [string,string,LucideIcon,string]]:[])];
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{tiles.map(([label,value,Icon,note])=><Metric key={label} label={label} value={value} Icon={Icon} note={note} loading={loading}/>)}</div>}
function RecentActivity(){const q=useNotifications(5); if(q.isPending) return <div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-10 w-full"/>)}</div>; if(q.isError) return <p className="text-sm text-muted-foreground">We couldn’t load your recent activity.</p>; if(!q.data.length) return <p className="text-sm text-muted-foreground">No activity yet. Updates about your listings and account will appear here.</p>;
  return <div className="space-y-4">{q.data.map(x=><div key={x.id} className="flex gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${x.read_at?'bg-muted-foreground/30':'bg-primary'}`}/><div className="min-w-0"><b className="text-sm">{x.title}</b>{x.body&&<p className="text-sm text-muted-foreground">{x.body}</p>}</div><span className="ml-auto shrink-0 text-xs text-muted-foreground">{timeAgo(x.created_at)}</span></div>)}<Link to="/dashboard/notifications" className="block text-sm font-semibold text-primary">View all notifications</Link></div>}
function SavedVehicles(){const uid=useUserId(); const {isSaved,toggle,ready}=useFavourites(); const q=useQuery({queryKey:queryKeys.favouriteVehicles(uid??'anon'),queryFn:listMyFavouriteVehicles,enabled:Boolean(uid)});
  if(q.isPending) return <LoadingGrid/>; if(q.isError) return <ErrorState message="We couldn’t load your saved vehicles." onRetry={()=>void q.refetch()}/>;
  // Hide cards the moment they're un-saved, before the refetch finishes.
  const items=ready?q.data.filter(v=>isSaved(v.id)):q.data; if(!items.length) return <><EmptyState title="No saved vehicles yet" body="Tap the heart on any vehicle to keep it here."/><div className="mt-4 text-center"><Button asChild><Link to="/vehicles">Browse vehicles</Link></Button></div></>;
  return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(v=><VehicleCard key={v.id} v={v} saved onSave={()=>v.id&&toggle(v.id)}/>)}</div>}
function NotificationsList(){const uid=useUserId(); const queryClient=useQueryClient(); const q=useNotifications(100); const [busy,setBusy]=useState(false);
  const unread=(q.data??[]).filter(x=>!x.read_at).map(x=>x.id);
  const markAll=async()=>{setBusy(true); try{await markNotificationsRead(unread); if(uid){await queryClient.invalidateQueries({queryKey:queryKeys.notifications(uid)}); void queryClient.invalidateQueries({queryKey:queryKeys.stats(uid)});}}catch(e){toast.error(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}};
  if(q.isPending) return <Panel title="Recent notifications"><div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-12 w-full"/>)}</div></Panel>; if(q.isError) return <ErrorState message="We couldn’t load your notifications." onRetry={()=>void q.refetch()}/>; if(!q.data.length) return <EmptyState title="No notifications yet" body="We’ll let you know about your listings, reviews and account here."/>;
  return <Panel title={unread.length?`${unread.length} unread`:'Recent notifications'}>{unread.length>0&&<Button variant="outline" size="sm" className="mb-2" disabled={busy} onClick={()=>void markAll()}>{busy&&<Loader2 className="animate-spin"/>}Mark all as read</Button>}{q.data.map(x=>{const inner=<><Bell className={`size-5 shrink-0 ${x.read_at?'text-muted-foreground':'text-primary'}`}/><div className="min-w-0"><b className="text-sm">{x.title}</b>{x.body&&<p className="text-sm text-muted-foreground">{x.body}</p>}</div><span className="ml-auto shrink-0 text-xs text-muted-foreground">{timeAgo(x.created_at)}</span></>; const internal=safeRedirectPath(x.link); return internal?<Link key={x.id} to={internal as never} className={`flex gap-3 border-b py-4 last:border-0 hover:bg-accent/40 ${x.read_at?'':'font-medium'}`}>{inner}</Link>:<div key={x.id} className="flex gap-3 border-b py-4 last:border-0">{inner}</div>})}</Panel>}
function MyReviews(){const uid=useUserId(); const business=useMyBusiness(); const businessId=business.data?.business.id??null; const q=useQuery({queryKey:[...queryKeys.reviewsAbout(uid??'anon'),businessId],queryFn:()=>listReviewsAbout({businessId,sellerId:uid}),enabled:Boolean(uid)&&!business.isPending});
  if(q.isPending) return <LoadingGrid/>; if(q.isError) return <ErrorState message="We couldn’t load your reviews." onRetry={()=>void q.refetch()}/>; if(!q.data.length) return <EmptyState title="No reviews yet" body="Reviews from buyers you’ve dealt with will appear here."/>;
  return <div className="space-y-3">{q.data.map(r=><Panel key={r.id} title={r.reviewer_name??'Caryandi user'}><div className="flex gap-1" aria-label={`${r.rating} out of 5`}>{Array.from({length:r.rating??0}).map((_,i)=><Star key={i} className="size-4 fill-warning text-warning"/>)}</div>{r.body&&<p className="mt-3 text-sm text-muted-foreground">{r.body}</p>}{r.created_at&&<p className="mt-2 text-xs text-muted-foreground">{timeAgo(r.created_at)}</p>}</Panel>)}</div>}
/** Business accounts manage their public business profile above their personal details. */
function BusinessProfileSection(){const auth=useAuth(); if(auth.status!=='signed-in'||!isBusinessAccount(auth.account.profile.account_type)) return null; return <div className="mb-8"><BusinessProfileForm/><h2 className="mt-10 text-lg font-semibold">Your personal details</h2><p className="mb-4 text-sm text-muted-foreground">Your own account, separate from the business.</p></div>}
