import {useEffect,useRef,useState,type FormEvent} from 'react'; import {useNavigate,useRouter,useRouterState} from '@tanstack/react-router'; import {useQuery} from '@tanstack/react-query'; import {SlidersHorizontal,Grid2X2,List,MapPin} from 'lucide-react'; import {Button} from '@/components/ui/button'; import {Input} from '@/components/ui/input'; import {Label} from '@/components/ui/label'; import {Checkbox} from '@/components/ui/checkbox'; import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select'; import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from '@/components/ui/sheet'; import {PageHero} from './section'; import {VehicleCard,DirectoryCard,PartCard,SellerCard} from './cards'; import {services,agents,parts} from '@/data/mock-data'; import {EmptyState,ErrorState} from './states';
import {useFavourites} from '@/lib/marketplace/hooks'; import {getMakeOptions,type VehicleSearchResult} from '@/lib/vehicles/vehicle-service'; import {SORTS,activeFilterCount,type VehicleFilters,type VehicleSort} from '@/lib/vehicles/filters'; import {CONDITIONS,DUTY_STATUSES,FUEL_TYPES,PROVINCES,REGISTRATION_STATUSES,TRANSMISSIONS,formatNumber,formatPrice,labelOf,type Province} from '@/lib/vehicles/vehicle-options'; import type {SellerSummary} from '@/lib/marketplace/seller-service';
const ANY='any';
const PRICE_RANGES:ReadonlyArray<readonly [string,string,number|undefined,number|undefined]>=[['u100','Under K100,000',undefined,100000],['100-250','K100,000 – K250,000',100000,250000],['250-500','K250,000 – K500,000',250000,500000],['500-1m','K500,000 – K1,000,000',500000,1000000],['o1m','Over K1,000,000',1000000,undefined]];
const YEAR_OPTIONS=[2022,2020,2018,2015,2012,2010,2005] as const;
function priceRangeKey(f:VehicleFilters){return PRICE_RANGES.find(([,,min,max])=>min===f.minPrice&&max===f.maxPrice)?.[0];}
/** Copy of the filters without the given keys (exactOptionalPropertyTypes forbids setting them to undefined). */
function without(f:VehicleFilters,...keys:Array<keyof VehicleFilters>):VehicleFilters{const next={...f}; for(const k of keys) delete next[k]; return next;}
function EnumSelect<T extends string>({label,value,options,onChange}:{label:string;value:T|undefined;options:ReadonlyArray<readonly [T,string]>;onChange:(v:T|undefined)=>void}){return <div><Label>{label}</Label><Select value={value??ANY} onValueChange={v=>onChange(v===ANY?undefined:v as T)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ANY}>Any {label.toLowerCase()}</SelectItem>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>}

/** Filter panel: edits a draft copy and applies it to the URL in one go. */
function Filters({filters,onApply}:{filters:VehicleFilters;onApply:(f:VehicleFilters)=>void}){
  const [draft,setDraft]=useState<VehicleFilters>(filters);
  useEffect(()=>setDraft(filters),[filters]);
  const makes=useQuery({queryKey:['vehicle-makes'],queryFn:getMakeOptions,staleTime:5*60_000});
  const set=<K extends keyof VehicleFilters>(key:K,value:VehicleFilters[K]|undefined)=>setDraft(d=>value===undefined?without(d,key):{...d,[key]:value});
  const makeOptions:Array<readonly [string,string]>=(makes.data??[]).map(m=>[m.make,`${m.make} (${m.count})`] as const);
  if(draft.make&&!makeOptions.some(([m])=>m.toLowerCase()===draft.make?.toLowerCase())) makeOptions.unshift([draft.make,draft.make]);
  return <div className="space-y-6">
    <EnumSelect label="Make" value={makeOptions.find(([m])=>m.toLowerCase()===draft.make?.toLowerCase())?.[0]} options={makeOptions} onChange={v=>set('make',v)}/>
    <EnumSelect label="Location" value={draft.province} options={PROVINCES} onChange={v=>set('province',v)}/>
    <div><Label>Price range</Label><Select value={priceRangeKey(draft)??(draft.minPrice!==undefined||draft.maxPrice!==undefined?'custom':ANY)} onValueChange={v=>{if(v==='custom') return; const r=PRICE_RANGES.find(([k])=>k===v); setDraft(d=>{const base=without(d,'minPrice','maxPrice'); return r?{...base,...(r[2]!==undefined?{minPrice:r[2]}:{}),...(r[3]!==undefined?{maxPrice:r[3]}:{})}:base;});}}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ANY}>Any price range</SelectItem>{(draft.minPrice!==undefined||draft.maxPrice!==undefined)&&!priceRangeKey(draft)&&<SelectItem value="custom" disabled>{draft.maxPrice!==undefined&&draft.minPrice===undefined?`Under ${formatPrice(draft.maxPrice)}`:draft.minPrice!==undefined&&draft.maxPrice===undefined?`Over ${formatPrice(draft.minPrice)}`:`${formatPrice(draft.minPrice??0)} – ${formatPrice(draft.maxPrice??0)}`}</SelectItem>}{PRICE_RANGES.map(([k,l])=><SelectItem key={k} value={k}>{l}</SelectItem>)}</SelectContent></Select></div>
    <div><Label>Year</Label><Select value={draft.minYear?String(draft.minYear):ANY} onValueChange={v=>set('minYear',v===ANY?undefined:Number(v))}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ANY}>Any year</SelectItem>{draft.minYear&&!YEAR_OPTIONS.includes(draft.minYear as never)&&<SelectItem value={String(draft.minYear)}>{draft.minYear} or newer</SelectItem>}{YEAR_OPTIONS.map(y=><SelectItem key={y} value={String(y)}>{y} or newer</SelectItem>)}</SelectContent></Select></div>
    <EnumSelect label="Transmission" value={draft.transmission} options={TRANSMISSIONS} onChange={v=>set('transmission',v)}/>
    <EnumSelect label="Fuel type" value={draft.fuel} options={FUEL_TYPES} onChange={v=>set('fuel',v)}/>
    <EnumSelect label="Condition" value={draft.condition} options={CONDITIONS} onChange={v=>set('condition',v)}/>
    <EnumSelect label="Registration" value={draft.registration} options={REGISTRATION_STATUSES} onChange={v=>set('registration',v)}/>
    <EnumSelect label="Import duty" value={draft.duty} options={DUTY_STATUSES} onChange={v=>set('duty',v)}/>
    <label className="flex items-center gap-2 text-sm"><Checkbox checked={Boolean(draft.verified)} onCheckedChange={c=>set('verified',c===true?true:undefined)}/> Verified listings only</label>
    <div className="grid gap-2"><Button className="w-full" onClick={()=>onApply(without(draft,'page'))}>Apply filters</Button>{activeFilterCount(filters)>0&&<Button variant="ghost" className="w-full" onClick={()=>onApply(without(filters,'make','province','minPrice','maxPrice','minYear','maxYear','maxMileage','transmission','fuel','condition','registration','duty','import','verified','page'))}>Clear filters</Button>}</div>
  </div>}

export type VehiclesPageData={result:VehicleSearchResult|null;error?:string};

/** /vehicles — results come from the route loader (rendered on the server); filters live in the URL. */
export function VehiclesPage({filters,data}:{filters:VehicleFilters;data:VehiclesPageData}){
  const navigate=useNavigate(); const router=useRouter();
  const loading=useRouterState({select:s=>s.status==='pending'});
  const {isSaved,toggle}=useFavourites();
  const [view,setView]=useState('grid'); const [sheetOpen,setSheetOpen]=useState(false);
  const [query,setQuery]=useState(filters.q??'');
  const sentQ=useRef(filters.q??''); const latest=useRef(filters); latest.current=filters;
  // Follow the URL (back button, filter links) but never overwrite what the visitor is still typing.
  useEffect(()=>{const q=filters.q??''; if(q!==sentQ.current){sentQ.current=q; setQuery(q);}},[filters.q]);
  const apply=(next:VehicleFilters)=>{setSheetOpen(false); void navigate({to:'/vehicles',search:next});};
  // Search as you type, without flooding the server or the browser history.
  useEffect(()=>{const text=query.trim().slice(0,80); if(text===sentQ.current.trim()) return; const t=window.setTimeout(()=>{sentQ.current=text; const f=latest.current; void navigate({to:'/vehicles',search:text?{...without(f,'page'),q:text}:without(f,'q','page'),replace:true});},450); return ()=>window.clearTimeout(t);},[query,navigate]);
  const result=data.result; const count=activeFilterCount(filters);
  const place=filters.province?`${labelOf(PROVINCES,filters.province)} Province`:'Across Zambia';
  return <><PageHero eyebrow="Vehicle marketplace" title="Find your next car in Zambia" body="Browse dealer and private listings with clear details, seller information and verification status."/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="hidden lg:block"><div className="sticky top-24 rounded-lg border bg-card p-5"><div className="mb-5 flex items-center gap-2 font-semibold"><SlidersHorizontal className="size-4"/>Filters{count>0&&<span className="ml-auto rounded-full bg-primary px-2 text-xs text-primary-foreground">{count}</span>}</div><Filters filters={filters} onApply={apply}/></div></aside><div className="min-w-0"><div className="grid gap-3 rounded-lg border bg-card p-3 sm:grid-cols-[1fr_auto_auto]"><Input value={query} onChange={e=>setQuery(e.target.value)} maxLength={80} aria-label="Search vehicles" placeholder="Search make, model or town"/><Select value={filters.sort??'newest'} onValueChange={v=>apply({...without(filters,'page','sort'),...(v==='newest'?{}:{sort:v as VehicleSort})})}><SelectTrigger className="sm:w-52"><SelectValue/></SelectTrigger><SelectContent>{SORTS.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select><div className="flex gap-2"><Sheet open={sheetOpen} onOpenChange={setSheetOpen}><SheetTrigger asChild><Button variant="outline" className="lg:hidden"><SlidersHorizontal/>Filters{count>0?` (${count})`:''}</Button></SheetTrigger><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Filter vehicles</SheetTitle></SheetHeader><div className="mt-6"><Filters filters={filters} onApply={apply}/></div></SheetContent></Sheet><Button variant={view==='grid'?'secondary':'ghost'} size="icon" onClick={()=>setView('grid')} aria-label="Grid view"><Grid2X2/></Button><Button variant={view==='list'?'secondary':'ghost'} size="icon" onClick={()=>setView('list')} aria-label="List view"><List/></Button></div></div>
  {!result?<div className="mt-5"><ErrorState message={data.error} onRetry={()=>void router.invalidate()}/></div>:<>
  <div className="mt-5 flex items-center justify-between text-sm"><b aria-live="polite">{formatNumber(result.total)} {result.total===1?'vehicle':'vehicles'}</b><span className="flex items-center gap-1 text-muted-foreground"><MapPin className="size-4"/>{place}</span></div>
  {result.items.length?<div className={`mt-4 grid gap-5 transition-opacity ${loading?'opacity-60':''} ${view==='grid'?'sm:grid-cols-2 xl:grid-cols-3':'grid-cols-1'}`}>{result.items.map(v=><VehicleCard key={v.id} v={v} saved={isSaved(v.id)} onSave={()=>v.id&&toggle(v.id)}/>)}</div>:<div className="mt-5 rounded-lg border border-dashed p-12 text-center"><h3 className="font-semibold">{result.total===0&&count===0&&!filters.q?'No vehicles listed yet':'No vehicles match your search'}</h3><p className="mt-1 text-sm text-muted-foreground">{result.total===0&&count===0&&!filters.q?'New listings appear here as soon as sellers publish them.':'Try another make, model or location, or clear some filters.'}</p></div>}
  {result.pageCount>1&&<nav aria-label="Pagination" className="mt-8 flex items-center justify-between gap-3"><Button variant="outline" disabled={result.page<=1} onClick={()=>apply(result.page<=2?without(filters,'page'):{...filters,page:result.page-1})}>Previous</Button><span className="text-sm text-muted-foreground">Page {result.page} of {result.pageCount}</span><Button variant="outline" disabled={result.page>=result.pageCount} onClick={()=>apply({...filters,page:result.page+1})}>Next</Button></nav>}
  </>}</div></div></main></>}

/** /sellers — dealerships and private sellers with live listings. */
export function SellersDirectory({search,sellers,error}:{search:{q?:string;province?:Province};sellers:SellerSummary[]|null;error?:string}){
  const navigate=useNavigate(); const router=useRouter();
  const [q,setQ]=useState(search.q??''); const [province,setProvince]=useState<string>(search.province??ANY);
  useEffect(()=>{setQ(search.q??''); setProvince(search.province??ANY);},[search.q,search.province]);
  const submit=(e:FormEvent)=>{e.preventDefault(); const text=q.trim().slice(0,80); const p=PROVINCES.find(([v])=>v===province)?.[0]; void navigate({to:'/sellers',search:{...(text?{q:text}:{}),...(p?{province:p}:{})}});};
  return <><PageHero eyebrow="Caryandi directory" title="Trusted sellers" body="Browse established dealers and active private sellers."/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><form onSubmit={submit} className="grid gap-3 rounded-lg border bg-card p-3 sm:grid-cols-[1fr_200px_auto]"><Input value={q} onChange={e=>setQ(e.target.value)} maxLength={80} aria-label="Search sellers" placeholder="Search sellers by name or town"/><Select value={province} onValueChange={setProvince}><SelectTrigger aria-label="Province"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ANY}>All locations</SelectItem>{PROVINCES.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select><Button type="submit">Search</Button></form>
  {!sellers?<div className="mt-6"><ErrorState message={error} onRetry={()=>void router.invalidate()}/></div>:sellers.length?<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{sellers.map(x=><SellerCard key={`${x.seller_kind}-${x.id}`} s={x}/>)}</div>:<div className="mt-6"><EmptyState title={search.q||search.province?'No sellers match your search':'No sellers yet'} body={search.q||search.province?'Try another name or location.':'Dealers and private sellers appear here once they list a vehicle.'}/></div>}
  </main></>}

export function DirectoryPage({type}:{type:'services'|'agents'|'parts'|'sellers'}){const title=type==='services'?'Mechanics & servicing':type==='agents'?'Vehicle import agents':type==='parts'?'Automotive parts':'Trusted sellers'; const body=type==='services'?'Compare trusted mechanics and service companies near you.':type==='agents'?'Find verified support for popular routes into Zambia.':type==='parts'?'Search new, used and reconditioned parts from local sellers.':'Browse established dealers and active private sellers.'; return <><PageHero eyebrow="Caryandi directory" title={title} body={body}/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="grid gap-3 rounded-lg border bg-card p-3 sm:grid-cols-[1fr_200px_auto]"><Input placeholder={`Search ${title.toLowerCase()}`}/><Select><SelectTrigger><SelectValue placeholder="All locations"/></SelectTrigger><SelectContent><SelectItem value="lusaka">Lusaka</SelectItem><SelectItem value="ndola">Ndola</SelectItem><SelectItem value="kitwe">Kitwe</SelectItem></SelectContent></Select><Button>Search</Button></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{type==='parts'?parts.map(p=><PartCard key={p.id} part={p}/>):type==='agents'?agents.map(x=><DirectoryCard key={x.id} item={x} kind="agent"/>):type==='sellers'?services.slice(0,2).map((x,i)=><DirectoryCard key={x.id} item={{...x,id:i?'copperbelt-motors':'autoworld-zambia',name:i?'Copperbelt Motors':'Autoworld Zambia',type:i?'Dealer':'Verified dealer',detail:'Quality inspected vehicles with transparent seller information.'}}/>):services.map(x=><DirectoryCard key={x.id} item={x}/>)}</div></main></>}
